### ISSUE TITLE
pull

### ISSUE THREAD

**Issue by JanaPaulino** [reprograma/On8-logica-js#27]
@natalialuizas mesmo fazendo o pull da minha branch da minha pasta de exercícios deu conflito no pull. Você me diz o que aconteceu please? E não finalizei todos os exercícios, mas, foi boa a experiência.
Tks.

**Comment by natalialuizads** [comment]
Oi Jana, você subiu também os exemplos que criamos na aula, eu resolvi os conflitos. :)
